[package]
name = "uwb_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-serial = "5.4.1"
tokio-util = "0.7"
num_enum = "0.7"
clap = { version = "4.5.48", features = ["derive"] }
